Dependency: Update unplugin dependency version to 2.3.11
I've found that when bumping tanstack router plugin in our project, that unplugin is not updated along with it, this results in build errors like this:

```
file:///path/to/node_modules/unplugin/dist/rspack/loaders/transform.js:11
        const res = await plugin.transform.call(Object.assign({}, this._compilation && createBuildContext(this._compiler, this._compilation, this), context), source, id);
                                           ^

TypeError: plugin.transform.call is not a function
    at Object.transform (file:///path/to/node_modules//node_modules/unplugin/dist/rspack/loaders/transform.js:11:37)
    at LOADER_EXECUTION (/path/to/node_modules/@rspack/core/dist/index.js:5520:18)
    at runSyncOrAsync2 (/path/to/node_modules/@rspack/core/dist/index.js:5521:6)
    at node:internal/util:495:21
    at new Promise (<anonymous>)
    at runSyncOrAsync2 (node:internal/util:481:12)
    at isomorphoicRun (/path/to/node_modules/@rspack/core/dist/index.js:6309:23)
    at runLoaders (/path/to/node_modules/@rspack/core/dist/index.js:6365:56)
```

Updating to 2.3.11 resolves these build errors as the implementation in the RSPack handler has changed somewhere along the way.